// ============================================================
// Agrigator — демо-данные (искусственный список курсов/репетиторов)
// ============================================================
window.SEED = {
  exams: ['IELTS', 'TOEFL', 'SAT', 'ACT', 'IB', 'A-Level', 'AP', 'GMAT', 'GRE', 'ЕНТ', 'NUET'],
  cities: ['Онлайн', 'Алматы', 'Астана', 'Шымкент'],

  courses: [
    {
      id: 'c1', type: 'course', title: 'IELTS Intensive 7.5+', provider: 'BilimHub',
      exams: ['IELTS'], price: 85000, priceUnit: 'мес', format: 'hybrid', city: 'Алматы',
      duration: '2 месяца', groupSize: 'до 8 человек', level: 'Upper-Intermediate+',
      rating: 4.9, students: 1240, sponsored: true, aiVerified: true,
      emoji: '🇬🇧', gradient: 'g1',
      description: 'Интенсивная подготовка к IELTS с фокусом на Writing и Speaking. Ежедневные мок-тесты, личный куратор и AI-ассистент на каждом занятии, который отслеживает прогресс и даёт обратную связь после урока.',
      features: ['AI-ассистент на занятиях', 'Ежедневные мок-тесты', 'Личный куратор', 'Гарантия результата или возврат денег', 'Чат с преподавателем 24/7'],
      schedule: 'Пн–Пт 19:00–21:00, мок-тесты по субботам',
      scoreStats: { metric: 'IELTS Band', before: 5.8, after: 7.2, sampleSize: 312, passRate: 91 },
      trial: true, trialFree: true,
      videoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
      bookingUrl: 'https://calendly.com/bilimhub/intro',
      contacts: { instagram: 'bilimhub.kz', telegram: 'bilimhub', whatsapp: '77071234501', phone: '+7 707 123 45 01', email: 'hello@bilimhub.kz' },
      source: 'manual', moneyBack: true
    },
    {
      id: 'c2', type: 'course', title: 'SAT 1500+ Bootcamp', provider: 'Almaty Prep Academy',
      exams: ['SAT'], price: 120000, priceUnit: 'мес', format: 'offline', city: 'Алматы',
      duration: '3 месяца', groupSize: 'до 6 человек', level: 'Advanced',
      rating: 4.8, students: 860, sponsored: true, aiVerified: true,
      emoji: '📐', gradient: 'g2',
      description: 'Буткемп для тех, кто целится в топ-университеты США. Digital SAT формат, адаптивные тренажёры, разбор каждой ошибки. Результаты выпускников подтверждены AI-верификацией по официальным score reports.',
      features: ['Digital SAT тренажёры', 'Adaptive practice tests', 'Эссе-менторство', 'College counseling в подарок'],
      schedule: 'Вт/Чт/Сб 15:00–18:00',
      scoreStats: { metric: 'SAT Score', before: 1180, after: 1510, sampleSize: 204, passRate: 88 },
      trial: true, trialFree: false,
      videoUrl: 'https://www.youtube.com/embed/aqz-KE-bpKQ',
      bookingUrl: 'https://calendly.com/almatyprep/call',
      contacts: { instagram: 'almatyprep', telegram: 'almatyprep', whatsapp: '77071234502', phone: '+7 707 123 45 02', email: 'info@almatyprep.kz' },
      source: 'manual', moneyBack: true
    },
    {
      id: 'c3', type: 'course', title: 'IELTS с нуля: 5.5 → 6.5', provider: 'EduWay',
      exams: ['IELTS'], price: 45000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '3 месяца', groupSize: 'до 12 человек', level: 'Pre-Intermediate',
      rating: 4.6, students: 2100, sponsored: false, aiVerified: true,
      emoji: '✈️', gradient: 'g3',
      description: 'Курс для тех, кто начинает подготовку с нуля. Плавный вход в формат экзамена, много практики Listening и Reading, поддержка кураторов.',
      features: ['Записи всех уроков', 'Домашки с проверкой', 'Telegram-сообщество'],
      schedule: 'Пн/Ср/Пт 20:00–21:30',
      scoreStats: { metric: 'IELTS Band', before: 4.9, after: 6.4, sampleSize: 540, passRate: 84 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/eduway/demo',
      contacts: { instagram: 'eduway.kz', telegram: 'eduwaykz', whatsapp: '77071234503', phone: '+7 707 123 45 03', email: 'team@eduway.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c4', type: 'course', title: 'SAT Math Mastery', provider: 'Tarqyn School',
      exams: ['SAT'], price: 60000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '2 месяца', groupSize: 'до 10 человек', level: 'Intermediate+',
      rating: 4.7, students: 530, sponsored: false, aiVerified: false,
      emoji: '🧮', gradient: 'g4',
      description: 'Только математическая секция SAT: от Heart of Algebra до Advanced Math. Цель — 750+ по Math.',
      features: ['Банк из 3000+ задач', 'Еженедельные мини-моки', 'Разбор ошибок 1-на-1'],
      schedule: 'Вт/Чт 19:00–20:30',
      scoreStats: { metric: 'SAT Math', before: 580, after: 760, sampleSize: 150, passRate: 86 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/tarqyn/intro',
      contacts: { instagram: 'tarqyn.school', telegram: 'tarqyn', whatsapp: '77071234504', phone: '+7 707 123 45 04', email: 'hi@tarqyn.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c5', type: 'course', title: 'IB Math AA/AI HL Support', provider: 'IB Masters',
      exams: ['IB'], price: 95000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: 'весь учебный год', groupSize: 'до 5 человек', level: 'HL',
      rating: 4.9, students: 310, sponsored: false, aiVerified: true,
      emoji: '🎯', gradient: 'g5',
      description: 'Сопровождение по IB Math (Analysis & Approaches / Applications & Interpretation, HL и SL). Подготовка к Internal Assessment и финальным экзаменам, цель — 6–7 баллов.',
      features: ['Преподаватели — IB examiners', 'Помощь с IA', 'Past papers с разбором'],
      schedule: 'Гибкое расписание под школу',
      scoreStats: { metric: 'IB Grade', before: 4.1, after: 6.3, sampleSize: 96, passRate: 93 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/ibmasters/call',
      contacts: { instagram: 'ib.masters', telegram: 'ibmasters', whatsapp: '77071234505', phone: '+7 707 123 45 05', email: 'care@ibmasters.kz' },
      source: 'manual', moneyBack: true
    },
    {
      id: 'c6', type: 'course', title: 'A-Level Physics (CIE/Edexcel)', provider: 'Cambridge Route',
      exams: ['A-Level'], price: 90000, priceUnit: 'мес', format: 'hybrid', city: 'Астана',
      duration: '6 месяцев', groupSize: 'до 6 человек', level: 'AS/A2',
      rating: 4.8, students: 240, sponsored: false, aiVerified: false,
      emoji: '⚛️', gradient: 'g6',
      description: 'Полная подготовка к A-Level Physics: теория, лабораторные навыки, past papers CIE и Edexcel. Цель — A*/A.',
      features: ['Разбор past papers с 2015 года', 'Лабораторный практикум', 'Предикт-оценка каждый месяц'],
      schedule: 'Сб/Вс 11:00–13:00',
      scoreStats: { metric: '% A*/A', before: 22, after: 78, sampleSize: 88, passRate: 78 },
      trial: true, trialFree: false,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/cambridgeroute/intro',
      contacts: { instagram: 'cambridge.route', telegram: 'cambridgeroute', whatsapp: '77071234506', phone: '+7 707 123 45 06', email: 'office@cambridgeroute.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c7', type: 'course', title: 'TOEFL iBT 100+', provider: 'LinguaPro',
      exams: ['TOEFL'], price: 70000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '2 месяца', groupSize: 'до 10 человек', level: 'Intermediate+',
      rating: 4.5, students: 670, sponsored: false, aiVerified: true,
      emoji: '🗽', gradient: 'g1',
      description: 'Подготовка к TOEFL iBT с симуляциями реального интерфейса экзамена и AI-оценкой Speaking-ответов.',
      features: ['AI-оценка Speaking', 'Симулятор интерфейса ETS', 'Шаблоны для Writing'],
      schedule: 'Пн/Ср 19:30–21:00',
      scoreStats: { metric: 'TOEFL Score', before: 78, after: 103, sampleSize: 178, passRate: 82 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/linguapro/demo',
      contacts: { instagram: 'linguapro.kz', telegram: 'linguapro', whatsapp: '77071234507', phone: '+7 707 123 45 07', email: 'go@linguapro.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c8', type: 'course', title: 'ЕНТ Интенсив: математика + физика', provider: 'Daryn Centre',
      exams: ['ЕНТ'], price: 35000, priceUnit: 'мес', format: 'offline', city: 'Шымкент',
      duration: '4 месяца', groupSize: 'до 15 человек', level: '11 класс',
      rating: 4.4, students: 1800, sponsored: false, aiVerified: false,
      emoji: '🇰🇿', gradient: 'g2',
      description: 'Системная подготовка к ЕНТ по профильным предметам. Еженедельные пробные тестирования в формате ЕНТ.',
      features: ['Пробное ЕНТ каждую неделю', 'Рейтинг группы', 'Родительские отчёты'],
      schedule: 'Пн–Сб 16:00–18:00',
      scoreStats: { metric: 'Балл ЕНТ', before: 72, after: 116, sampleSize: 640, passRate: 89 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/daryn/visit',
      contacts: { instagram: 'daryn.centre', telegram: 'daryncentre', whatsapp: '77071234508', phone: '+7 707 123 45 08', email: 'info@daryn.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c9', type: 'course', title: 'NUET Preparation Pro', provider: 'NU Track',
      exams: ['NUET'], price: 55000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '5 месяцев', groupSize: 'до 12 человек', level: '11–12 класс',
      rating: 4.7, students: 420, sponsored: true, aiVerified: true,
      emoji: '🏛️', gradient: 'g3',
      description: 'Подготовка к NUET (Nazarbayev University Entrance Test): Critical Thinking и Math. Преподаватели — выпускники NU.',
      features: ['Преподаватели — выпускники NU', 'База NUET-style задач', 'Mock days раз в месяц'],
      schedule: 'Вт/Чт/Сб 18:00–19:30',
      scoreStats: { metric: 'NUET Score', before: 95, after: 152, sampleSize: 130, passRate: 74 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/nutrack/intro',
      contacts: { instagram: 'nu.track', telegram: 'nutrack', whatsapp: '77071234509', phone: '+7 707 123 45 09', email: 'hello@nutrack.kz' },
      source: 'manual', moneyBack: true
    },
    {
      id: 'c10', type: 'course', title: 'GMAT 700+ для MBA', provider: 'MBA Lab',
      exams: ['GMAT'], price: 150000, priceUnit: 'курс', format: 'online', city: 'Онлайн',
      duration: '10 недель', groupSize: 'до 6 человек', level: 'Advanced',
      rating: 4.8, students: 190, sponsored: false, aiVerified: true,
      emoji: '💼', gradient: 'g4',
      description: 'Подготовка к GMAT Focus Edition для поступления в топовые бизнес-школы. Data Insights, Quant, Verbal.',
      features: ['Официальные моки GMAC', 'Стратегия тайм-менеджмента', 'Консультация по admissions'],
      schedule: 'Сб/Вс 10:00–12:00',
      scoreStats: { metric: 'GMAT Score', before: 540, after: 695, sampleSize: 64, passRate: 81 },
      trial: false, trialFree: false,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/mbalab/strategy',
      contacts: { instagram: 'mba.lab', telegram: 'mbalab', whatsapp: '77071234510', phone: '+7 707 123 45 10', email: 'apply@mbalab.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c11', type: 'course', title: 'A-Level Mathematics', provider: 'Cambridge Route',
      exams: ['A-Level'], price: 90000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '6 месяцев', groupSize: 'до 8 человек', level: 'AS/A2',
      rating: 4.6, students: 280, sponsored: false, aiVerified: false,
      emoji: '📊', gradient: 'g5',
      description: 'Pure Math, Mechanics и Statistics для CIE и Edexcel. Структурированная программа от AS до A2.',
      features: ['Конспекты по всем темам', 'Топик-тесты после каждого блока', 'Past papers marathon перед сессией'],
      schedule: 'Пн/Ср/Пт 18:00–19:30',
      scoreStats: { metric: '% A*/A', before: 30, after: 81, sampleSize: 102, passRate: 81 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/cambridgeroute/math',
      contacts: { instagram: 'cambridge.route', telegram: 'cambridgeroute', whatsapp: '77071234506', phone: '+7 707 123 45 06', email: 'office@cambridgeroute.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c12', type: 'course', title: 'AP Calculus BC', provider: 'APex School',
      exams: ['AP'], price: 80000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '4 месяца', groupSize: 'до 8 человек', level: 'AP',
      rating: 4.5, students: 150, sponsored: false, aiVerified: false,
      emoji: '∫', gradient: 'g6',
      description: 'Подготовка к AP Calculus BC на 5 баллов. FRQ-практика и разбор экзаменационных стратегий College Board.',
      features: ['FRQ-разборы каждую неделю', 'AP Classroom интеграция', 'Предикт скора'],
      schedule: 'Вт/Чт 20:00–21:30',
      scoreStats: { metric: '% на 4–5', before: 35, after: 87, sampleSize: 54, passRate: 87 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/apex/calc',
      contacts: { instagram: 'apex.school', telegram: 'apexschool', whatsapp: '77071234512', phone: '+7 707 123 45 12', email: 'team@apexschool.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c13', type: 'course', title: 'IELTS Weekend Group', provider: 'EduWay',
      exams: ['IELTS'], price: 38000, priceUnit: 'мес', format: 'offline', city: 'Астана',
      duration: '3 месяца', groupSize: 'до 14 человек', level: 'Intermediate',
      rating: 4.3, students: 940, sponsored: false, aiVerified: false,
      emoji: '📅', gradient: 'g1',
      description: 'Бюджетная группа выходного дня для работающих и занятых студентов. Полное покрытие всех четырёх секций.',
      features: ['Занятия только Сб/Вс', 'Доступ к онлайн-платформе', 'Мини-моки раз в 2 недели'],
      schedule: 'Сб/Вс 12:00–15:00',
      scoreStats: { metric: 'IELTS Band', before: 5.4, after: 6.5, sampleSize: 260, passRate: 79 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/eduway/weekend',
      contacts: { instagram: 'eduway.kz', telegram: 'eduwaykz', whatsapp: '77071234503', phone: '+7 707 123 45 03', email: 'team@eduway.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c14', type: 'course', title: 'GRE Quant 165+', provider: 'MBA Lab',
      exams: ['GRE'], price: 130000, priceUnit: 'курс', format: 'online', city: 'Онлайн',
      duration: '8 недель', groupSize: 'до 8 человек', level: 'Advanced',
      rating: 4.6, students: 110, sponsored: false, aiVerified: false,
      emoji: '🧠', gradient: 'g2',
      description: 'Quant-секция GRE для поступающих в магистратуру и PhD. Глубокая проработка Data Interpretation.',
      features: ['ETS official guides', 'Адаптивные домашки', 'Стратегии для shortened GRE'],
      schedule: 'Пн/Чт 19:00–21:00',
      scoreStats: { metric: 'GRE Quant', before: 152, after: 166, sampleSize: 42, passRate: 83 },
      trial: false, trialFree: false,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/mbalab/gre',
      contacts: { instagram: 'mba.lab', telegram: 'mbalab', whatsapp: '77071234510', phone: '+7 707 123 45 10', email: 'apply@mbalab.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c15', type: 'course', title: 'SAT Verbal Sprint', provider: 'Almaty Prep Academy',
      exams: ['SAT'], price: 65000, priceUnit: 'мес', format: 'online', city: 'Онлайн',
      duration: '6 недель', groupSize: 'до 10 человек', level: 'Intermediate+',
      rating: 4.5, students: 380, sponsored: false, aiVerified: true,
      emoji: '📚', gradient: 'g3',
      description: 'Спринт по Reading & Writing секции Digital SAT. Техники работы с короткими текстами нового формата.',
      features: ['Vocabulary system', 'Grammar bootcamp', '2 полных мока'],
      schedule: 'Пн/Ср/Пт 17:00–18:30',
      scoreStats: { metric: 'SAT R&W', before: 560, after: 710, sampleSize: 118, passRate: 80 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/almatyprep/verbal',
      contacts: { instagram: 'almatyprep', telegram: 'almatyprep', whatsapp: '77071234502', phone: '+7 707 123 45 02', email: 'info@almatyprep.kz' },
      source: 'manual', moneyBack: false
    },
    {
      id: 'c16', type: 'course', title: 'IB Extended Essay Mentorship', provider: 'IB Masters',
      exams: ['IB'], price: 70000, priceUnit: 'курс', format: 'online', city: 'Онлайн',
      duration: '8 недель', groupSize: '1-на-1', level: 'DP1/DP2',
      rating: 4.9, students: 85, sponsored: false, aiVerified: false,
      emoji: '✍️', gradient: 'g4',
      description: 'Индивидуальное менторство по Extended Essay: выбор темы, research design, драфты и финальная вычитка. Цель — A/B по EE.',
      features: ['Ментор — IB examiner', '6 индивидуальных сессий', 'Дедлайн-трекер'],
      schedule: 'Индивидуально',
      scoreStats: { metric: '% A/B по EE', before: 28, after: 84, sampleSize: 47, passRate: 84 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/ibmasters/ee',
      contacts: { instagram: 'ib.masters', telegram: 'ibmasters', whatsapp: '77071234505', phone: '+7 707 123 45 05', email: 'care@ibmasters.kz' },
      source: 'manual', moneyBack: true
    }
  ],

  tutors: [
    {
      id: 't1', type: 'tutor', name: 'Айгерим Сапарова', exams: ['IELTS'], subjects: 'IELTS: все секции, упор на Writing',
      price: 12000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 6,
      rating: 5.0, students: 320, sponsored: false, aiVerified: true,
      photo: 'https://i.pravatar.cc/240?img=47', gradient: 'g1', online: true, responseTime: '~30 минут',
      ownScores: [{ exam: 'IELTS', score: '8.5', verified: true }],
      education: 'КИМЭП, MA TESOL; CELTA',
      languages: ['Казахский', 'Русский', 'Английский'],
      bio: 'Готовлю к IELTS 6 лет. Мои студенты в среднем растут на +1.4 балла за 2 месяца. Сама сдала IELTS на 8.5 (подтверждено AI-верификацией Agrigator). Работаю с AI-ассистентом на уроках — после каждого занятия вы получаете автоматический отчёт.',
      achievements: ['Топ-1 репетитор платформы 2025', '40+ студентов с Band 7.5+', 'Официальный партнёр AI-ассистента'],
      scoreStats: { metric: 'IELTS Band', before: 5.9, after: 7.3, sampleSize: 145, passRate: 92 },
      trial: true, trialFree: true,
      videoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
      bookingUrl: 'https://calendly.com/aigerim-ielts/trial',
      contacts: { instagram: 'aigerim.ielts', telegram: 'aigerim_ielts', whatsapp: '77011110001', phone: '+7 701 111 00 01', email: 'aigerim@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't2', type: 'tutor', name: 'Данияр Ермеков', exams: ['SAT'], subjects: 'SAT Math + Reading & Writing',
      price: 15000, priceUnit: 'час', format: 'hybrid', city: 'Алматы', experience: 5,
      rating: 4.9, students: 210, sponsored: true, aiVerified: true,
      photo: 'https://i.pravatar.cc/240?img=12', gradient: 'g2', online: true, responseTime: '~1 час',
      ownScores: [{ exam: 'SAT', score: '1580', verified: true }],
      education: 'Nazarbayev University, BSc Mathematics',
      languages: ['Казахский', 'Русский', 'Английский'],
      bio: 'Сдал SAT на 1580 (800 Math). Учу решать Digital SAT быстро и без паники: стратегии, тайм-менеджмент, разбор ловушек College Board. Среди студентов — поступившие в NYU, KAIST и NU.',
      achievements: ['25 студентов с 1500+', 'Автор телеграм-канала о SAT на 18k подписчиков'],
      scoreStats: { metric: 'SAT Score', before: 1210, after: 1490, sampleSize: 98, passRate: 85 },
      trial: true, trialFree: false,
      videoUrl: 'https://www.youtube.com/embed/aqz-KE-bpKQ',
      bookingUrl: 'https://calendly.com/daniyar-sat/trial',
      contacts: { instagram: 'daniyar.sat', telegram: 'daniyar_sat', whatsapp: '77011110002', phone: '+7 701 111 00 02', email: 'daniyar@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't3', type: 'tutor', name: 'Алия Нурланқызы', exams: ['IELTS', 'TOEFL'], subjects: 'IELTS / TOEFL, Speaking-клубы',
      price: 10000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 4,
      rating: 4.8, students: 280, sponsored: false, aiVerified: true,
      photo: 'https://i.pravatar.cc/240?img=44', gradient: 'g3', online: false, responseTime: '~2 часа',
      ownScores: [{ exam: 'IELTS', score: '8.0', verified: true }, { exam: 'TOEFL', score: '114', verified: true }],
      education: 'ЕНУ им. Гумилёва, иностранная филология',
      languages: ['Казахский', 'Русский', 'Английский', 'Турецкий'],
      bio: 'Двойная специализация IELTS + TOEFL. Помогу выбрать, какой экзамен сдавать именно вам, и подготовиться без лишнего стресса. Веду разговорные клубы дважды в неделю.',
      achievements: ['Speaking-клуб 2 раза в неделю бесплатно для учеников', '95% студентов достигают цели с первой попытки'],
      scoreStats: { metric: 'IELTS Band', before: 5.6, after: 7.0, sampleSize: 117, passRate: 88 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/aliya-english/trial',
      contacts: { instagram: 'aliya.english', telegram: 'aliya_english', whatsapp: '77011110003', phone: '+7 701 111 00 03', email: 'aliya@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't4', type: 'tutor', name: 'Мария Ким', exams: ['IB'], subjects: 'IB Math AA/AI (HL/SL), IA mentorship',
      price: 14000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 7,
      rating: 4.9, students: 150, sponsored: false, aiVerified: false,
      photo: 'https://i.pravatar.cc/240?img=32', gradient: 'g4', online: true, responseTime: '~45 минут',
      ownScores: [{ exam: 'IB', score: '43/45', verified: false }],
      education: 'University of Toronto, BSc Mathematics; экс-преподаватель IB-школы',
      languages: ['Русский', 'Английский', 'Корейский'],
      bio: '7 лет преподаю IB Math, из них 4 года — в аккредитованной IB-школе. Знаю критерии оценивания изнутри, помогаю довести IA до 18–20 баллов.',
      achievements: ['Экс-преподаватель IB World School', 'Средний рост студентов: +2 IB grade'],
      scoreStats: { metric: 'IB Grade', before: 4.0, after: 6.2, sampleSize: 76, passRate: 91 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/maria-ib/trial',
      contacts: { instagram: 'maria.ibmath', telegram: 'maria_ibmath', whatsapp: '77011110004', phone: '+7 701 111 00 04', email: 'maria@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't5', type: 'tutor', name: 'Тимур Абенов', exams: ['A-Level', 'AP'], subjects: 'A-Level / AP Physics и Math',
      price: 13000, priceUnit: 'час', format: 'hybrid', city: 'Астана', experience: 8,
      rating: 4.7, students: 190, sponsored: false, aiVerified: true,
      photo: 'https://i.pravatar.cc/240?img=59', gradient: 'g5', online: false, responseTime: '~3 часа',
      ownScores: [{ exam: 'A-Level', score: 'A*A*A', verified: true }],
      education: 'Imperial College London, MSc Physics',
      languages: ['Казахский', 'Русский', 'Английский'],
      bio: 'Выпускник Imperial College. Готовлю к A-Level и AP по физике и математике 8 лет. Сильная сторона — объяснять сложное простыми словами и связывать темы между собой.',
      achievements: ['12 студентов поступили в UK Top-10', 'Разработал собственный задачник по Mechanics'],
      scoreStats: { metric: '% A*/A', before: 25, after: 80, sampleSize: 84, passRate: 80 },
      trial: true, trialFree: false,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/timur-physics/trial',
      contacts: { instagram: 'timur.physics', telegram: 'timur_physics', whatsapp: '77011110005', phone: '+7 701 111 00 05', email: 'timur@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't6', type: 'tutor', name: 'Жанна Тулегенова', exams: ['ЕНТ'], subjects: 'ЕНТ: математика и матграмотность',
      price: 6000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 10,
      rating: 4.8, students: 540, sponsored: false, aiVerified: false,
      photo: 'https://i.pravatar.cc/240?img=49', gradient: 'g6', online: true, responseTime: '~1 час',
      ownScores: [],
      education: 'КазНПУ им. Абая, учитель математики высшей категории',
      languages: ['Казахский', 'Русский'],
      bio: 'Школьный учитель с 10-летним стажем. Готовлю к ЕНТ системно: диагностика, закрытие пробелов, еженедельные пробники. Занимаюсь на казахском и русском.',
      achievements: ['Средний балл учеников по математике: 34/40', 'Грант-холдеры каждый год'],
      scoreStats: { metric: 'Балл ЕНТ', before: 70, after: 112, sampleSize: 210, passRate: 90 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/zhanna-ent/trial',
      contacts: { instagram: 'zhanna.ent', telegram: 'zhanna_ent', whatsapp: '77011110006', phone: '+7 701 111 00 06', email: 'zhanna@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't7', type: 'tutor', name: 'Александр Ли', exams: ['SAT', 'ACT'], subjects: 'SAT/ACT Math',
      price: 12000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 4,
      rating: 4.6, students: 130, sponsored: false, aiVerified: true,
      photo: 'https://i.pravatar.cc/240?img=11', gradient: 'g1', online: true, responseTime: '~20 минут',
      ownScores: [{ exam: 'SAT', score: '800 Math', verified: true }],
      education: 'КБТУ, Computer Science',
      languages: ['Русский', 'Английский'],
      bio: 'Math 800 на SAT. Специализируюсь только на математике SAT и ACT — глубоко, быстро, по системе. Бесплатная диагностика на первом занятии.',
      achievements: ['800/800 SAT Math (AI-verified)', 'Средний рост по Math: +160 баллов'],
      scoreStats: { metric: 'SAT Math', before: 590, after: 750, sampleSize: 66, passRate: 86 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/alex-satmath/trial',
      contacts: { instagram: 'alex.satmath', telegram: 'alex_satmath', whatsapp: '77011110007', phone: '+7 701 111 00 07', email: 'alex@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't8', type: 'tutor', name: 'Камила Досжан', exams: ['NUET'], subjects: 'NUET: Critical Thinking + Math',
      price: 8000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 3,
      rating: 4.7, students: 95, sponsored: false, aiVerified: false,
      photo: 'https://i.pravatar.cc/240?img=45', gradient: 'g2', online: false, responseTime: '~2 часа',
      ownScores: [{ exam: 'NUET', score: '174/180', verified: false }],
      education: 'Nazarbayev University, Economics (3 курс)',
      languages: ['Казахский', 'Русский', 'Английский'],
      bio: 'Студентка NU, сдала NUET на 174/180. Объясняю Critical Thinking так, как объяснила бы младшей сестре — на реальных прошлогодних задачах.',
      achievements: ['174/180 собственный результат', '70% учеников проходят на грант NU'],
      scoreStats: { metric: 'NUET Score', before: 98, after: 149, sampleSize: 40, passRate: 70 },
      trial: true, trialFree: true,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/kamila-nuet/trial',
      contacts: { instagram: 'kamila.nuet', telegram: 'kamila_nuet', whatsapp: '77011110008', phone: '+7 701 111 00 08', email: 'kamila@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't9', type: 'tutor', name: 'Ерлан Мухтаров', exams: ['GMAT', 'GRE'], subjects: 'GMAT / GRE Quant + Verbal',
      price: 18000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 9,
      rating: 4.9, students: 85, sponsored: false, aiVerified: true,
      photo: 'https://i.pravatar.cc/240?img=68', gradient: 'g3', online: true, responseTime: '~4 часа',
      ownScores: [{ exam: 'GMAT', score: '760', verified: true }],
      education: 'INSEAD MBA; экс-консультант Big3',
      languages: ['Русский', 'Английский'],
      bio: 'GMAT 760, MBA INSEAD. Готовлю взрослых профессионалов к GMAT/GRE и помогаю со стратегией поступления в бизнес-школы. Жёсткий и структурный подход.',
      achievements: ['Студенты поступали в INSEAD, LBS, Wharton', 'Средний рост GMAT: +140'],
      scoreStats: { metric: 'GMAT Score', before: 560, after: 700, sampleSize: 38, passRate: 84 },
      trial: false, trialFree: false,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/erlan-gmat/strategy',
      contacts: { instagram: 'erlan.gmat', telegram: 'erlan_gmat', whatsapp: '77011110009', phone: '+7 701 111 00 09', email: 'erlan@agrigator.kz' },
      source: 'manual'
    },
    {
      id: 't10', type: 'tutor', name: 'Sophie Anderson', exams: ['IELTS'], subjects: 'IELTS Speaking (native speaker)',
      price: 20000, priceUnit: 'час', format: 'online', city: 'Онлайн', experience: 5,
      rating: 4.9, students: 160, sponsored: true, aiVerified: false,
      photo: 'https://i.pravatar.cc/240?img=24', gradient: 'g4', online: true, responseTime: '~1 час',
      ownScores: [],
      education: 'University of Edinburgh; CELTA, экс-экзаменатор IELTS',
      languages: ['Английский'],
      bio: 'Native speaker from the UK, former IELTS examiner. I help students break the Band 7 barrier in Speaking with examiner-level feedback. Lessons fully in English.',
      achievements: ['Экс-экзаменатор IELTS Speaking', '90% студентов получают 7.0+ по Speaking'],
      scoreStats: { metric: 'Speaking Band', before: 6.0, after: 7.4, sampleSize: 88, passRate: 90 },
      trial: true, trialFree: false,
      videoUrl: '',
      bookingUrl: 'https://calendly.com/sophie-ielts/trial',
      contacts: { instagram: 'sophie.ielts', telegram: 'sophie_ielts', whatsapp: '77011110010', phone: '+7 701 111 00 10', email: 'sophie@agrigator.kz' },
      source: 'manual'
    }
  ],

  reviews: [
    { id: 'r1', targetType: 'course', targetId: 'c1', userName: 'Дана С.', rating: 5, verified: true, date: '2026-05-12', beforeScore: '6.0', afterScore: '7.5', text: 'За 2 месяца подняла с 6.0 до 7.5! AI-отчёты после каждого урока — реально полезная вещь, видно прогресс по каждому критерию.' },
    { id: 'r2', targetType: 'course', targetId: 'c1', userName: 'Арман Т.', rating: 5, verified: true, date: '2026-04-28', beforeScore: '5.5', afterScore: '7.0', text: 'Куратор отвечает даже ночью, моки каждую субботу. Writing разобрали до косточек.' },
    { id: 'r3', targetType: 'course', targetId: 'c1', userName: 'Aliya M.', rating: 4, verified: false, date: '2026-03-15', text: 'Сильный курс, но темп очень высокий. Если нет базы Upper-Int — будет тяжело.' },
    { id: 'r4', targetType: 'course', targetId: 'c2', userName: 'Бекзат Н.', rating: 5, verified: true, date: '2026-05-02', beforeScore: '1230', afterScore: '1540', text: '1540 на майском SAT! Адаптивные тренажёры — топ, после них реальный тест показался легче.' },
    { id: 'r5', targetType: 'course', targetId: 'c2', userName: 'Карина Ж.', rating: 4, verified: true, date: '2026-02-20', beforeScore: '1150', afterScore: '1460', text: 'Дорого, но того стоит. College counseling в подарок реально помог со списком вузов.' },
    { id: 'r6', targetType: 'course', targetId: 'c3', userName: 'Нурлан А.', rating: 5, verified: true, date: '2026-05-20', beforeScore: '4.5', afterScore: '6.5', text: 'Начинал почти с нуля. Очень комфортный темп, записи уроков спасали, когда пропускал.' },
    { id: 'r7', targetType: 'course', targetId: 'c3', userName: 'Мадина К.', rating: 4, verified: false, date: '2026-04-01', text: 'Хороший курс за свои деньги. Группы большие, но кураторы тащат.' },
    { id: 'r8', targetType: 'course', targetId: 'c5', userName: 'Tomiris', rating: 5, verified: true, date: '2026-05-08', beforeScore: '4', afterScore: '7', text: 'IA вытянули с 11 до 19 баллов. Преподаватель — реальный examiner, видит работу как на грейдинге.' },
    { id: 'r9', targetType: 'course', targetId: 'c8', userName: 'Айбек Д.', rating: 4, verified: true, date: '2026-05-25', beforeScore: '78', afterScore: '118', text: '118 на пробном республиканском! Рейтинг группы мотивирует, родителям нравятся отчёты.' },
    { id: 'r10', targetType: 'course', targetId: 'c9', userName: 'Диас О.', rating: 5, verified: true, date: '2026-04-18', beforeScore: '101', afterScore: '156', text: 'Прошёл на грант NU. Critical thinking прокачали с нуля, mock days — лучшее, что было.' },
    { id: 'r11', targetType: 'tutor', targetId: 't1', userName: 'Жанель Б.', rating: 5, verified: true, date: '2026-06-01', beforeScore: '6.5', afterScore: '8.0', text: 'Айгерим — лучшая. Writing с 6.0 до 7.5 за 6 недель. AI-отчёт после урока сразу в телеграм.' },
    { id: 'r12', targetType: 'tutor', targetId: 't1', userName: 'Олжас К.', rating: 5, verified: true, date: '2026-05-14', text: 'Очень структурно, без воды. Стоит каждого тенге.' },
    { id: 'r13', targetType: 'tutor', targetId: 't2', userName: 'Алишер С.', rating: 5, verified: true, date: '2026-05-30', beforeScore: '1280', afterScore: '1520', text: '1520! Данияр объясняет ловушки College Board так, что начинаешь их видеть за километр.' },
    { id: 'r14', targetType: 'tutor', targetId: 't2', userName: 'Инкар А.', rating: 4, verified: false, date: '2026-03-22', text: 'Сильный препод, но расписание забито — бронируйте слоты заранее.' },
    { id: 'r15', targetType: 'tutor', targetId: 't3', userName: 'Аружан Т.', rating: 5, verified: true, date: '2026-05-19', beforeScore: '5.5', afterScore: '7.0', text: 'Speaking-клубы — огонь. Перестала бояться говорить уже после третьей недели.' },
    { id: 'r16', targetType: 'tutor', targetId: 't4', userName: 'Daniel P.', rating: 5, verified: true, date: '2026-04-10', text: 'Maria saved my IA. Got 19/20. She knows exactly what examiners want.' },
    { id: 'r17', targetType: 'tutor', targetId: 't6', userName: 'Гульнара (мама ученика)', rating: 5, verified: true, date: '2026-05-28', beforeScore: '64', afterScore: '109', text: 'Сын поднял математику с 24 до 36 баллов. Жанна Сергеевна — учитель от бога.' },
    { id: 'r18', targetType: 'tutor', targetId: 't7', userName: 'Тамерлан Е.', rating: 5, verified: true, date: '2026-06-03', beforeScore: '620', afterScore: '780', text: 'Math 780. Александр отвечает в телеграме за 10 минут, разбирает любую задачу.' },
    { id: 'r19', targetType: 'tutor', targetId: 't10', userName: 'Асель М.', rating: 5, verified: true, date: '2026-05-22', beforeScore: '6.0', afterScore: '7.5', text: 'Speaking 7.5 после 6.0! Sophie даёт фидбек как настоящий экзаменатор — потому что она им была.' },
    { id: 'r20', targetType: 'tutor', targetId: 't9', userName: 'Рустам Б.', rating: 5, verified: true, date: '2026-04-05', beforeScore: '590', afterScore: '720', text: 'GMAT 720 с третьей попытки (до Ерлана было две неудачных). Жёстко, но работает.' }
  ],

  users: [
    {
      id: 'u1', name: 'Администратор', email: 'admin@agrigator.kz', password: 'admin123',
      role: 'admin', plan: 'pro', planUntil: '2027-01-01', avatarColor: '#7c3aed',
      favorites: [], bookings: [], reports: [], verifiedExams: [], createdAt: '2025-09-01'
    },
    {
      id: 'u2', name: 'Аймер', email: 'user@demo.kz', password: 'demo123',
      role: 'user', plan: 'free', planUntil: null, avatarColor: '#0ea5e9',
      favorites: ['course:c1', 'tutor:t1'], bookings: [], reports: [], verifiedExams: [], createdAt: '2026-02-14'
    },
    {
      id: 'u3', name: 'Pro Студент', email: 'pro@demo.kz', password: 'demo123',
      role: 'user', plan: 'pro', planUntil: '2026-12-31', avatarColor: '#16a34a',
      favorites: ['tutor:t2'], bookings: [], reports: [], verifiedExams: [{ exam: 'IELTS', score: '7.0', date: '2026-03-10' }], createdAt: '2026-01-20'
    }
  ],

  // Лиды, найденные парсером объявлений (Instagram / OLX / Telegram)
  leads: [
    {
      id: 'l1', source: 'Instagram', url: 'https://instagram.com/p/demo1', foundAt: '2026-06-09', status: 'new',
      rawText: '🔥 Набор в группу IELTS! Гарантия 7.0+ 💪 Преподаватель с Band 8.5. Занятия онлайн 3 раза в неделю. Цена 50 000 тг/мес. Пробный урок бесплатно! Пишите в директ @ielts_pro_almaty',
      parsed: { title: 'IELTS группа 7.0+', exam: 'IELTS', price: 50000, format: 'online', instagram: 'ielts_pro_almaty' }
    },
    {
      id: 'l2', source: 'OLX', url: 'https://olx.kz/obyavlenie/demo2', foundAt: '2026-06-10', status: 'new',
      rawText: 'Репетитор по SAT Math. Студент NU, собственный результат 790. 8000 тг/час, онлайн. Первое занятие — диагностика бесплатно. Тел: +7 700 555 44 33',
      parsed: { title: 'Репетитор SAT Math (NU)', exam: 'SAT', price: 8000, format: 'online', phone: '+7 700 555 44 33' }
    },
    {
      id: 'l3', source: 'Telegram', url: 'https://t.me/edu_ads_kz/4521', foundAt: '2026-06-10', status: 'new',
      rawText: 'Группа подготовки к NUET. Critical Thinking + Math. Старт 1 июля. 45000 в месяц, мест мало! Контакт: @nuet_start',
      parsed: { title: 'NUET группа, старт 1 июля', exam: 'NUET', price: 45000, format: 'online', telegram: 'nuet_start' }
    }
  ]
};
